apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jollof-db-credentials
  namespace: jollof-run
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "jollof-run/db-credentials"
        objectType: "secretsmanager"
        objectAlias: "db-credentials"
