apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: jollof-run
  labels:
    app: backend
    app.kubernetes.io/part-of: jollof-run
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::609898225411:role/jollof-run-backend-irsa
    eks.amazonaws.com/token-expiration: '3600'
